version: '3'
services:
  icedb:
    image: postgres:latest
    environment:
      POSTGRES_USER: "dev"
      POSTGRES_PASSWORD: "dev"
      POSTGRES_DB: "icedb"
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/1-init.sql
      - ./data.sql:/docker-entrypoint-initdb.d/2-data.sql
    ports:
      - "5432:5432"

  ice_api:
    build: ..
    ports:
      - "8080:8080"
    environment:
      SPRING_PROFILES_ACTIVE: dev
      HOST: icedb
      POSTGRES_USER: "dev"
      POSTGRES_PASSWORD: "dev"
      SERVER_PORT: "8080"
      DATABASE_SERVER_PORT: "5432"
    depends_on:
      - icedb