spring:
  application:
    name: ice api
  datasource:
    url: "jdbc:postgresql://${HOST:localhost}:5432/icedb"
    password: "${POSTGRES_PASSWORD:dev}"
    username: "${POSTGRES_USER:dev}"
    driver-class-name: "org.postgresql.Driver"

  jpa:
    defer-datasource-initialization: true
    database: "POSTGRESQL"
    show-sql: true
    generate-ddl: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true

  jackson:
    default-property-inclusion: non_null

server:
  servlet:
    context-path: /api/v1
